Table usuarios {
  id int [pk, increment]
  nome varchar(120) [not null]
  email varchar(150) [not null, unique]
  senha_hash varchar(255) [not null]
  is_admin boolean [not null, default: false]
  criado_em datetime [not null]
  atualizado_em datetime [not null]
}

Table enderecos {
  id int [pk, increment]
  usuario_id int [not null, ref: > usuarios.id]
  titulo varchar(80) [not null]
  logradouro varchar(150) [not null]
  numero varchar(20) [not null]
  bairro varchar(80) [not null]
  cidade varchar(80) [not null]
  estado varchar(2) [not null]
  cep varchar(10) [not null]
  complemento varchar(120)
  principal boolean [not null, default: false]
  criado_em datetime [not null]
}

Table preferencias {
  id int [pk, increment]
  usuario_id int [not null, unique, ref: > usuarios.id]
  tema varchar(20) [not null]
  som_habilitado boolean [not null, default: true]
  biometria_habilitada boolean [not null, default: false]
  atualizacao_pedidos boolean [not null, default: true]
  ofertas_habilitadas boolean [not null, default: true]
  alerta_estoque boolean [not null, default: false]
  atualizado_em datetime [not null]
}

Table produtos {
  id int [pk, increment]
  nome varchar(120) [not null]
  preco decimal(10,2) [not null]
  categoria varchar(80) [not null]
  descricao text [not null]
  cor_destaque varchar(20)
  formato varchar(40)
  estoque int [not null, default: 0]
  ativo boolean [not null, default: true]
  criado_em datetime [not null]
  atualizado_em datetime [not null]
}

Table carrinhos {
  id int [pk, increment]
  usuario_id int [not null, ref: > usuarios.id]
  status varchar(20) [not null, default: 'ativo']
  criado_em datetime [not null]
  atualizado_em datetime [not null]
}

Table carrinho_itens {
  id int [pk, increment]
  carrinho_id int [not null, ref: > carrinhos.id]
  produto_id int [not null, ref: > produtos.id]
  quantidade int [not null, default: 1]
  selecionado boolean [not null, default: true]
  preco_unitario decimal(10,2) [not null]
  criado_em datetime [not null]
}

Table favoritos {
  id int [pk, increment]
  usuario_id int [not null, ref: > usuarios.id]
  produto_id int [not null, ref: > produtos.id]
  criado_em datetime [not null]

  indexes {
    (usuario_id, produto_id) [unique]
  }
}

Table pedidos {
  id int [pk, increment]
  usuario_id int [not null, ref: > usuarios.id]
  endereco_id int [not null, ref: > enderecos.id]
  codigo varchar(20) [not null, unique]
  status varchar(30) [not null]
  valor_total decimal(10,2) [not null]
  data_pedido datetime [not null]
  atualizado_em datetime [not null]
}

Table pedido_itens {
  id int [pk, increment]
  pedido_id int [not null, ref: > pedidos.id]
  produto_id int [not null, ref: > produtos.id]
  quantidade int [not null]
  preco_unitario decimal(10,2) [not null]
  subtotal decimal(10,2) [not null]
}
